### ISSUE TITLE
Experiment with switching the backend to use jsdom

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/spec-generator#13]
See https://github.com/w3c/spec-generator/pull/12#issuecomment-127658034

When there’s time to try it, switching to using `jsdom` would be worth trying experimentally.

**Comment by darobin** [comment]
I reckon this might be more of a ReSpec bug TBH :)

**Comment by sideshowbarker** [comment]
Closing this as stale. If anybody else prefers to keep it open of course feel free to re-open it.
