### ISSUE TITLE
QS parameters aren't parsed correctly

### ISSUE THREAD

**Issue by deniak** [w3c/spec-generator#170]
@marcoscaceres spec-generator fails at generating the right "This version" url when passing the shortName parameter, e.g. [screen-orientation](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/screen-orientation/index.html?specStatus=WD;shortName=screen-orientation).
It seems to work well if you remove `;shortName=screen-orientation` from the url but it used to work in the past. Do you think it can be related to a recent (~1 month) change to respec?

**Comment by marcoscaceres** [comment]
Oh, could you please try “&” instead of “;”?

**Comment by deniak** [comment]
Yeah, it's working better. Is it related to a change with respec?

**Comment by marcoscaceres** [comment]
Yes, sorry. We made that change a while ago. We were supporting the old “;” delimiter but we stopped at some point. I’m on my phone so can’t look up the exact commit history, but happy to find when we changed that if you’d like.

**Comment by deniak** [comment]
@marcoscaceres thanks for checking

**Comment by deniak** [comment]
@plehegar I've updated the echidna wiki but all the manifests using ';' will have to be updated. I'll try to submit PRs in the next couple of days for the repos I've identified.

**Comment by plehegar** [comment]
@deniak , thank you.

**Comment by marcoscaceres** [comment]
If it’s looking like it’s going to be a ton of work, let me know and I can see about reverting back to the legacy “;”. I’d prefer not to, because we have newer APIs like URLSearchParam that we rely on for this, but if we broke too much stuff...

**Comment by deniak** [comment]
@marcoscaceres it should be fine. It's a quick fix when you know what's the problem.

**Comment by marcoscaceres** [comment]
/me takes a look in the mirror 👀 😅😇

**Comment by deniak** [comment]
sorry, my comment was confusing. I meant it's easy to fix the manifests for these repositories so don't revert your changes in respec just for that.

**Comment by marcoscaceres** [comment]
No, it was clear. I’m just making silly jokes because I broke things 🙂
