### ISSUE TITLE
Prevent www.w3.org/scripts/ from being triggered

### ISSUE THREAD

**Issue by plehegar** [w3c/spec-generator#21]
eg. http://webaudio.github.io/web-audio-api/
don't allow MathJax from running otherwise it will generate extra markup that shouldn't be replaced.

**Comment by tripu** [comment]
Thanks for filing this one, @plehegar.
Just a comment: scripts should be enabled/disabled individually, not necessarily depending on whether they're loaded from w3.org or from some other place, yes?

**Comment by plehegar** [comment]
correct.
here we want to disable in the spec-generator any script in www.w3.org/scripts/. Those should be left as-is in the generated document, without them touching the doc in the spec-generator.
