### ISSUE TITLE
Spec-generator times out when given a different kind of document

### ISSUE THREAD

**Issue by tripu** [w3c/spec-generator#27]
eg, [when given `https://rawgit.com/w3c/browser-payment-api/fpwd/fpwd/paymentrequest.html`](https://labs.w3.org/spec-generator/?type=respec&url=https://rawgit.com/w3c/browser-payment-api/fpwd/fpwd/paymentrequest.html) (which is a valid spec already, nothing to _generate_ there), the answer is

``` json
{"error": "Processing timed out."}
```

That message is misleading. Can we detect this scenario and tell the user something more meaningful?

**Comment by deniak** [comment]
The problem comes from `respec2html` and not the spec-generator itself. From what I understand, @marcoscaceres fixed the timeout issue in the latest versions of respec. However, I think the recent updates to respec break spec-generator. We will need to update it.

**Comment by tripu** [comment]
In which ways would the latest respec be incompatible with spec-generator, @deniak @marcoscaceres?

I just `npm update`d spec-generator here, it picked up respec `3.2.116`, and seems to run OK locally. (But it's a very poor test, admittedly.)

On the other hand, [`http://localhost:3000/?url=https://rawgit.com/w3c/browser-payment-api/fpwd/fpwd/paymentrequest.html&type=respec`](http://localhost:3000/?url=https://rawgit.com/w3c/browser-payment-api/fpwd/fpwd/paymentrequest.html&type=respec) still returns `{"error": "Processing timed out."}`. Maybe the timeout issue is different to this other one (ie, detect that the document can't be generated, and fail sooner).

**Comment by marcoscaceres** [comment]
@tripu, let me ship new ReSpec. It uses Electron instead of Phantomjs ... it may make things worst or not. Hopefully not 💃

**Comment by marcoscaceres** [comment]
Ok, shipped 3.2.118

**Comment by deniak** [comment]
@marcoscaceres what's the requirement about the node.js version? It's working fine with node 5.10.1 but I see some errors when using node 4.4.3

**Comment by marcoscaceres** [comment]
Yeah, you need 5.10... I also jumped the shark a bit... still publishing .. npm is being slow to accept the new version :(

**Comment by tripu** [comment]
Yeah, I saw the tag wasn't on npm yet, so I edited `package.json` to have `git://github.com/w3c/respec.git#v3.2.118` as the version.

Still timing out for the non-document (Node `v.4.4.3`).

**Comment by marcoscaceres** [comment]
@tripu, is it possible to use on a newer version of Node?

**Comment by marcoscaceres** [comment]
@tripu, btw, that URL (https://rawgit.com/w3c/browser-payment-api/fpwd/fpwd/paymentrequest.html) is a generated file, it's no a respec document. Which is probably why it's timing out.

**Comment by marcoscaceres** [comment]
Yeah, that seems to be the problem. You want this one:
https://rawgit.com/w3c/browser-payment-api/fpwd/specs/paymentrequest.html

**Comment by tripu** [comment]
> tripu, is it possible to use on a newer version of Node? 

If you mean if we could deploy Node.js `5.x` in production, I think the answer is yes.
I think we're sticking to the `4.x` series purely because it's the LTS one, to be more conservative in production. There might be limitations to switch to `5`, but I don't know any off the top of my head.

> @tripu, btw, that URL (https://rawgit.com/w3c/browser-payment-api/fpwd/fpwd/paymentrequest.html) is a generated file, it's no a respec document. Which is probably why it's timing out.

That's precisely the bug I'm reporting: if it's not a ReSpec document, instead of timing out, tell the user that the input is wrong in the first place (if at all possible; it helps discriminate causes for errors, and avoids confusion for silly users&nbsp;&mdash;&nbsp;like myself :) ).

**Comment by marcoscaceres** [comment]
@tripu I would never expect such sillyness from you! Only from myself. And fantastic idea. I will add that.

**Comment by marcoscaceres** [comment]
I implemented this a while a go, but forgot to report back: 
https://github.com/w3c/respec/blob/develop/tools/respecDocWriter.js#L99

You can probably close this?
