### ISSUE TITLE
{"error":"Navigation timeout of 30000 ms exceeded"}

### ISSUE THREAD

**Issue by jnurthen** [w3c/spec-generator#289]
curl -i "https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/aria/removeDefer/index.html"
HTTP/2 500 
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 51
etag: W/"33-B9tscI3tM+SOKGsBsSIaNUqebh8"
date: Mon, 30 Mar 2020 22:34:09 GMT
strict-transport-security: max-age=15552015; preload
public-key-pins: pin-sha256="cN0QSpPIkuwpT6iP2YjEo1bEwGpH/yiUn6yhdy+HNto="; pin-sha256="WGJkyYjx1QMdMe0UqlyOKXtydPDVrk7sl2fV+nNm1r4="; pin-sha256="LrKdTxZLRTvyHM4/atX2nquX9BeHRZMCxg3cf4rhc2I="; max-age=864000

{"error":"Navigation timeout of 30000 ms exceeded"}

Works fine with spec-generator locally

**Comment by marcoscaceres** [comment]
There seems to be an error in the spec itself:
https://raw.githack.com/w3c/aria/removeDefer/index.html

```
[Error] Error when calling function . See developer console. – undefined
	(anonymous function) (respec-w3c-common:1:4170)
	(anonymous function) (respec-w3c-common:1:3590)
	forEach
	o (respec-w3c-common:1:3580)
	(anonymous function) (respec-w3c-common:1:3607)
	forEach
	o (respec-w3c-common:1:3580)
	(anonymous function) (respec-w3c-common:800:195672)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] TypeError: undefined is not an object (evaluating 'respecConfig.definitionMap[item]')
	(anonymous function) (respec-w3c-common:1:3694)
	forEach
	o (respec-w3c-common:1:3580)
	(anonymous function) (respec-w3c-common:800:195672)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob```

**Comment by jnurthen** [comment]
Fixed the errors - I still can't get it to run through spec-generator on labs.

This works fine on local.

**Comment by deniak** [comment]
The process was stuck on the server. I restarted it and it should now work better.
