### ISSUE TITLE
{"error":"Navigation timeout of 30000 ms exceeded"}

### ISSUE THREAD

**Issue by jnurthen** [w3c/spec-generator#292]
again

Example URLs that fail
https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/aria/removeDefer/index.html

https://labs.w3.org/spec-generator/?type=respec&url=https://rawcdn.githack.com/w3c/aria-practices/c74e8e46b38c7df5f4c1079f8d3dedf5373af1ab/aria-practices.html&isPreview=true

**Comment by jnurthen** [comment]
@deniak @marcoscaceres this seems to be happening frequently. Is there anything that can be done to have a way to restart the server if jobs keep on failing?

**Comment by marcoscaceres** [comment]
I guess we need to figure out what the root cause is that is causing it to stall on the server. There is a regression somewhere or some dependency is locking things up. 

@deniak, any output on the server for you?

**Comment by deniak** [comment]
Looking at the logs below, it seems the second spec is missing the respecConfig.
However, for the first one, I don't see any errors in the logs. I did restart spec-generator and it's working again.
Memory on the server looks fine but I do see some remaining chrome processes still running so I suspect they aren't properly killed when there's an error. I'll try to debug more later today.

```
Generating https://rawcdn.githack.com/w3c/aria-practices/c74e8e46b38c7df5f4c1079f8d3dedf5373af1ab/aria-practices.html?isPreview=true&publishDate=2020-04-14
ESC[31m😱 ReSpec error: ESC[36mReferenceError: respecConfig is not defined Uncaught ReferenceError: respecConfig is not defined [object ErrorEvent]ESC[31mESC[39m
ESC[31m😱 ReSpec error: ESC[36mReferenceError: biblio is not defined Uncaught ReferenceError: biblio is not defined [object ErrorEvent]ESC[31mESC[39m
```

**Comment by marcoscaceres** [comment]
cc'ing @sidvishnoi., who can look at respec2html to see if anything in the generator might need more robust exit strategy to kill the process.

**Comment by marcoscaceres** [comment]
@jnurthen, sent a PR to fix the reference errors:
https://github.com/w3c/aria-practices/pull/1376

**Comment by deniak** [comment]
I looked a bit and it seems the process gets stuck on the [document generation](https://github.com/w3c/respec/blob/develop/tools/respecDocWriter.js#L93) and the browser never gets closed. This can be reproduced with the following command:
```
$ ./tools/respec2html.js -s https://rawcdn.githack.com/w3c/aria-practices/c74e8e46b38c7df5f4c1079f8d3dedf5373af1ab/aria-practices.html
😱 ReSpec error: ReferenceError: respecConfig is not defined Uncaught ReferenceError: respecConfig is not defined [object ErrorEvent]
😱 ReSpec error: ReferenceError: biblio is not defined Uncaught ReferenceError: biblio is not defined [object ErrorEvent]
😱 ReSpec error: Error when calling function n. See developer console.
😱 ReSpec error: TypeError: Cannot convert undefined or null to object

```

**Comment by sidvishnoi** [comment]
Thanks for a reduced test case @deniak. I'll investigate this in a while.

**Comment by sidvishnoi** [comment]
Released ReSpec v25.6.1 with a fix for stalling on unresolved promise.

**Comment by marcoscaceres** [comment]
Legend! Hopefully it makes the W3C server happy.

**Comment by deniak** [comment]
I just redeployed and I confirm the processes are correctly killed. Thanks @sidvishnoi !

**Comment by jnurthen** [comment]
Thanks all.
