### ISSUE TITLE
Return feedback earlier (useful to debug timeouts)

### ISSUE THREAD

**Issue by tripu** [w3c/spec-generator#30]
I'm not very familiar with spec-generator, but I hope this makes sense:

When [our instance of spec-generator](https://labs.w3.org/spec-generator/) crashes, or times out (sometimes due to memory issues), users are left with no information about the error.

Would it be possible to return _some_ information straight away, and keep on writing a &ldquo;log&rdquo; while possible, until it crashes or times out (if it does). Ideally, returning a partial response to the client, or writing to the JS console (for interactive usage)&nbsp;&mdash;&nbsp;but if that's not feasible given the current architecture (because I think no response is sent back until the whole document is processed), at least have sever-side logs that are more verbose?

eg, right now, when there are errors, on the server we see things like:

> Generating https://rawgit.com/w3c/coga/master/extension/index.html?publishDate=2016-09-14
> 😱 ReSpec error: [object Object]

which aren't terribly helpful.

**Comment by marcoscaceres** [comment]
@tripu, I'm on it.

**Comment by marcoscaceres** [comment]
Ok, covered generic cases with stack throw, and caught the actual error with that spec (their markup was invalid!): 

![screenshot 2016-09-20 14 40 37](https://cloud.githubusercontent.com/assets/870154/18657757/90da1654-7f40-11e6-8e76-6a6a9a46df16.png)

Waiting for PR to be reviewed. Will release in the next day or so.

**Comment by tripu** [comment]
Brilliant, @marcoscaceres, thanks!

(Yes, we found the issue with that particular spec already.)

**Comment by marcoscaceres** [comment]
Ok, just merged. Will release in a little bit 🍾

If you spot other regular issues the you think ReSpec could better help users with, please bubble them up to Shane and I.

**Comment by tripu** [comment]
Roger that :)

**Comment by tripu** [comment]
I think we can now close this one, right, @marcoscaceres?

**Comment by marcoscaceres** [comment]
Yep 👍 close it.
