### ISSUE TITLE
Some params in target url cannot be recognized when forget to encode

### ISSUE THREAD

**Issue by jennyliang220** [w3c/spec-generator#305]
## What breaks the tool
The url target url is: `https://w3c.github.io/screen-orientation/index.html?specStatus=WD&shortName=screen-orientation`

If we put the link behind url params, the [spec-generator link](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/screen-orientation/index.html?specStatus=WD&shortName=screen-orientation) is: `https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/screen-orientation/index.html?specStatus=WD&shortName=screen-orientation`

In spec-generator/server.js,
https://github.com/w3c/spec-generator/blob/493afc7961b10fc71325c6cb7a06f478ad35b7df/server.js#L37
since the target url is not encoded, we can only get `https://w3c.github.io/screen-orientation/index.html?specStatus=WD`, the `shortName` is lost (shortName in req.query).
![image](https://user-images.githubusercontent.com/8498677/82865548-92adf080-9f59-11ea-9c88-8da08a05cf89.png)
![image](https://user-images.githubusercontent.com/8498677/82863874-d141ac00-9f55-11ea-80de-24606e954704.png)

## Quick solution
This problem can be solved if we manually encode the target url (`&`->`%26`), so the spec-generator link is: `https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fw3c.github.io%2Fscreen-orientation%2Findex.html%3FspecStatus%3DWD%26shortName%3Dscreen-orientation`, this will solve the problem.
![image](https://user-images.githubusercontent.com/8498677/82864145-7d839280-9f56-11ea-8fc4-2c83c7788f36.png)

## More user-friendly solution
Letting our users encode url manually is not friendly enough, so I suggest:
A. We do #138 **Serve a simple form to submit a URL**, which we let the form to do the encoding. 
B. Also get `shortName` (and other possible querys in url like `type`) from req.query.

**Comment by deniak** [comment]
A form can be very handy indeed so +1 to add a form taking the url as parameter (there could be a 2nd param for the type but since we currently only support respec, it's not really useful).

Regarding the option B., there could actually be many more parameters that respec supports so we can simply pass a hardcoded property to respec.

**Comment by jennyliang220** [comment]
closed by https://github.com/w3c/spec-generator/pull/356
