### ISSUE TITLE
documentation for post feature

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/spec-generator#307]
It was [announced[(https://lists.w3.org/Archives/Public/spec-prod/2020JanMar/0002.html) that the spec-generator now supports post, but the [documentation](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#creating-a-static-snapshot-from-the-command-line) was actually put into the respec documentation. I'd like to see the documentation in the spec-generator documentation, where I can find it when I'm looking for it.

**Comment by deniak** [comment]
Sorry for the late reply. I only noticed that issue now. The documentation is now available in the wiki of this repository: https://github.com/w3c/spec-generator/wiki/Creating-a-Static-Snapshot-from-the-Command-Line
