### ISSUE TITLE
support post of tar

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/spec-generator#308]
For the new post feature, I would like the ability to upload a tar, in the way Echidna now supports. This is needed to be able to process additional files incorporated with the respec data-include feature, as well as to process auxiliary external scripts that work together with respec to tune formatting. I would be ok with the assumption that the Echidna tar feature supports, that the index.html file at the root of the tar is what it will actually do the processing on.

**Comment by deniak** [comment]
@michael-n-cooper can you point me to a document that relies on these `data-*` attributes and external scripts? This will be helpful to test that feature

**Comment by michael-n-cooper** [comment]
Sure. Most of my specs use respec data-include to some extent. The Web Content Accessibility Guidelines 2.2 uses them a lot, perhaps 100 include files. The index file is at https://github.com/w3c/wcag/blob/master/guidelines/index.html.

**Comment by deniak** [comment]
@michael-n-cooper I just deployed the support for the tarball (see https://github.com/w3c/spec-generator/wiki/Creating-a-Static-Snapshot-from-the-Command-Line) Let me know if there's any issue.
