### ISSUE TITLE
Getting 500 (curl exit 22) errors on Travis CI

### ISSUE THREAD

**Issue by nschonni** [w3c/spec-generator#35]
Seems like alot of builds have started to fail when they are cUrling from the spec generator.

```console
The command "curl "https://labs.w3.org/spec-generator/?type=respec&url=https://rawgit.com/w3c/aria-practices/master/aria-practices.html" -o index.html -f" failed and exited with 22 during .
```
Running on the local machine returns OK, running in the browser also returns OK.
Is there a user-agent filtering that was turned on recently?

Related https://github.com/w3c/aria-practices/issues/430

**Comment by marcoscaceres** [comment]
Odd... I wonder if ReSpec is up to date on the server? I see the package says 15.0.0, but we are now up to 15.5.0

**Comment by nschonni** [comment]
Not really a solution, but adding a 3*retry seemed to "fix" it. It seems to consistently fail the first attempt, but succeed the second time.

**Comment by deniak** [comment]
I've updated respec on the server and it seems to work better now.

**Comment by marcoscaceres** [comment]
woot!

**Comment by jnurthen** [comment]
I'm getting these same errors in the ARIA repository. Even with the retry -3 it fails.
When I run
`https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/aria/master/index.html`
I get 
`"Navigation Timeout Exceeded: 20000ms exceeded"`

Running spec-generator locally completes correctly.

**Comment by deniak** [comment]
@jnurthen does it work better now?

**Comment by marcoscaceres** [comment]
Works now 👍

**Comment by jnurthen** [comment]
Yes - works now. Thanks.
