### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by nschonni** [w3c/spec-generator#36]
Since sometimes things can timeout #35, would it make sense to publish this as an NPM package so the generation can run on local CI files?

Related to #430

**Comment by deniak** [comment]
Unfortunately publishing spec-generator on npm won't help since the timeout issues were related to an outdated version of respec on the server. When a new version is released, we need to make sure it's also deployed with spec-generator. I'll configure greenkeeper.io so we'll get a new PR after each release of the dependencies.

**Comment by marcoscaceres** [comment]
@deniak, can you also configure ReSpec to behave the same? I don't have access to rights to greenskeeper (because it's linked to the W3C Org). Or do I need to change ReSpec's package file instead to stop using "^"?

**Comment by nschonni** [comment]
thanks @marcoscaceres! 
I'm not sure it's possible to do a good isolated version of this or not. The problem i'm trying to solve is that the aria-practices repo can only rebuild it draft gh-pages after the page is published, rather than locally as part of the commit.

**Comment by marcoscaceres** [comment]
Yeah, that's a bit more involved. I don't recommend you do that per commit. If you want a preview of the spec, then just add this file to your repo:

https://github.com/w3c/payment-request/blob/gh-pages/.pr-preview.json

That will generate a link to a preview when you do a pull request. For example:
https://github.com/w3c/payment-request/pull/541

(see the diff | preview links)

**Comment by nschonni** [comment]
Thanks for the hint!
@michael-n-cooper have you thought of this method already?

**Comment by deniak** [comment]
> @deniak, can you also configure ReSpec to behave the same? I don't have access to rights to greenskeeper (because it's linked to the W3C Org). Or do I need to change ReSpec's package file instead to stop using "^"?

@marcoscaceres, greenkeeper is already enabled for the respec repository. My [PR](https://github.com/w3c/spec-generator/pull/37) only updates the versions syntax in packages.json so greenkeeper detects a minor version change.

**Comment by marcoscaceres** [comment]
>  My PR only updates the versions syntax in packages.json so greenkeeper detects a minor version change.

Ok, cool. Will try the same in ReSpec's package. Just wanted to confirm.
