### ISSUE TITLE
Bad Gateway?

### ISSUE THREAD

**Issue by plehegar** [w3c/spec-generator#5]
https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/manifest/?specStatus=WD;shortName=network-error-logging

works and returns a generated document, but

 https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/manifest/?specStatus=WD;shortName=appmanifest

... doesn't work and returns a Bad Gateway.

The second is the one that should work since it's using the correct shortName.
It seems that the system doesn't recognize the shortname but it does exist: http://www.w3.org/TR/appmanifest/ .

What's wrong there?

**Comment by darobin** [comment]
On 19/03/2015 21:17 , Philippe Le Hegaret wrote:
> The second is the one that should work since it's using the correct
> shortName.
> It seems that the system doesn't recognize the shortname but it does
> exist: http://www.w3.org/TR/appmanifest/ .
>
> What's wrong there?

I can't find the string "appmanifest" appearing anywhere in 
http://www.w3.org/2002/01/tr-automation/tr.rdf. That's likely to be the 
source of the problem: the spec-generator can't find the previous version.

-- 
Robin Berjon - http://berjon.com/ - @robinberjon

**Comment by plehegar** [comment]
Here is a fix in https://github.com/w3c/spec-generator/pull/6
And yes, appmanifest disappeared from tr.rf

**Comment by plehegar** [comment]
@tripu This should fix the problem encountered on Wednesday (well, tr.rdf will need to be fixed as well now)

**Comment by tripu** [comment]
Thanks, @plehegar. I'll let @darobin or @dontcallmedom merge your fix. We will update the instance of spec-generator in labs.w3.org together with the other tools next time.

**Comment by darobin** [comment]
The metadata extraction part is @dontcallmedom's code, I defer to him on this. A quick look LGTM.

**Comment by plehegar** [comment]
@tripu once merged, it would be good to deploy it sooner rather than later otherwise we'll keep messing tr.rdf ...

**Comment by darobin** [comment]
Speaking of deployment, have there been discussions of continuous deployment?

**Comment by plehegar** [comment]
no continuous deployment yet but a 2/3 weeks release cycle. Critical bug fix get deployed sooner.

**Comment by plehegar** [comment]
@tripu, the fix has been deployed. No more action needed.
