### ISSUE TITLE
Spec generator returning 404 on uploaded files

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/spec-generator#546]
For example:
http://labs.w3.org/spec-generator/uploads/oCQ7pE

Which [Spec Preview](http://github.com/tobie/pr-preview) attempted to create. This is affecting all specs that use PR preview 😢 

@deniak, see for example:
https://github.com/w3c/web-share/pull/234

**Comment by miketaylr** [comment]
See also https://github.com/w3c/permissions/pull/380
