### ISSUE TITLE
Propagate all errors originating in Respec

### ISSUE THREAD

**Issue by tripu** [w3c/spec-generator#55]
While debugging something for @vivienlacourba in `https://labs.w3.org/spec-generator/`, we noticed that the error from spec-generator on the browser was simply

    "error": "colors.info is not a function"

, while the Node.js logs on the server showed other issues:

    😱 ReSpec error: Document on track but no previous version: Add `previousMaturity`, and `previousPublishDate` to ReSpec's config.
    😱 ReSpec error: `specStatus` is "CR", but no `crEnd` is specified in Respec config.
    😱 ReSpec error: CR, PR, and REC documents need to have an `implementationReportURI` defined.

Would it be possible to pass along *all* errors/warnings originating in Respec to spec-generator, and return those to the user in the HTTP response?

Would that require changes in Respec? (I guess it would, since Respec writes those diagnostics to `stdout`/`stderr`&hellip;?)

Similar to #30, but not quite the same.

**Comment by marcoscaceres** [comment]
Sure, it's totally possible. I can either direct the output to into a provided stream, collect errors/warnings into an array, or just send back text. 

I'll investigate the "colors.info" error. That looks like a bug.

**Comment by marcoscaceres** [comment]
Fixed the  "colors.info" bug. Let me know what you prefer from here.

**Comment by tripu** [comment]
> *&ldquo;Fixed the &lsquo;colors.info&rsquo; bug.&rdquo;*

Thanks, @marcoscaceres.

**Comment by tripu** [comment]
> *&ldquo;Sure, it's totally possible. I can either direct the output to into a provided stream, collect errors/warnings into an array, or just send back text.&rdquo;*

Looking at the code of both Respec and spec-generator, I think it will be enough if `fetchAndWrite()` returned *all* errors and warnings it found while processing the document (instead of just the HTTP error code it gets from Nightmare, as it does now). In other words, [the error `msg` thrown](https://github.com/w3c/respec/blob/develop/tools/respecDocWriter.js#L83-L88) would include all warnings and errors.

That will not require any change in spec-generator, and users will start to see more verbose errors on the browser when processing fails.

WDYT?

**Comment by marcoscaceres** [comment]
Sounds good. I’ll poke around a bit to see how to best structure all the errors.

**Comment by marcoscaceres** [comment]
All errors are gathered now by ReSpec, so closing.
