### ISSUE TITLE
Parameters aren't correctly parsed

### ISSUE THREAD

**Issue by deniak** [w3c/spec-generator#57]
https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/wpub/?specStatus=FPWD;includePermalinks=false&publishDate=2017-12-05

https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/wpub/?specStatus=FPWD&publishDate=2017-12-05&includePermalinks=false

The 2 urls above don't give the same results. Also, `&publishDate` does create a snapshot with the date passed in parameter but `;publishDate` won't take the date into account.

**Comment by marcoscaceres** [comment]
ReSpec prefers "&".
