### ISSUE TITLE
Wrong previous version if the document has been published the same day

### ISSUE THREAD

**Issue by deniak** [w3c/spec-generator#7]
If a document has already been published and you run spec-generator the same day, the previous version is wrong because it's relying on `tr.rdf` which was updated during the last publication.

If the publication date and the date in `tr.rdf` are the same, spec-generator should take `rdf:obsoletes` as previous version.

**Comment by plehegar** [comment]
See https://github.com/w3c/spec-generator/pull/6

**Comment by plehegar** [comment]
#6 merged
